spring:
  application:
    # UNIQUE NAME OF THIS MICROSERVICE
    name: airport-boarding-service
  # ANSI CONSOLE OUTPUT (COLOR LOGS WILL BE DISPLAYED)
  output:
    ansi:
      enabled: ALWAYS
  # ZIPKIN SERVER URL
  zipkin:
    base-url: 'http://localhost:9411'

server:
  # TO RUN THIS MICROSERVICE ON RANDOM SERVER PORT 'server.port=0'
  # SERVER PORT OF THIS MICROSERVICE
  port: '8086'

# EUREKA SERVER URL
eureka:
  client:
    service:
      url:
        defaultZone: 'http://localhost:8761/eureka'

# SWAGGER-UI CUSTOM PATH
springdoc:
  swagger-ui:
    path: /swagger-ui.html

# ACTUATOR WEB ENDPOINTS EXPOSURE
management:
  endpoints:
    web:
      exposure:
        # EXPOSE ALL THE ACTUATOR WEB ENDPOINTS IF SECURITY IS NOT YOUR CONCERN!
        include: "*"
  # GET DETAIL INFORMATION OF ACTUATOR HEALTH ENDPOINT 
  endpoint:    
    health:
      show-details: always

airport:
  # AIRPORT-CHECKIN-SERVICE URL
  checkin:
    service:
      url: 'http://localhost:8085'
  # AIRPORT-CHECKING-SERVICE URL
  checking:
    service:
      url: 'http://localhost:8084'
  # AIRPORT-BOOKING-SERVICE URL
  booking:
    service:
      url: 'http://localhost:8083'
