FROM java:8

EXPOSE 8086

ADD target/airport-boarding-service-0.0.1-SNAPSHOT.jar airport-boarding-service-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "airport-boarding-service-0.0.1-SNAPSHOT.jar"]