FROM java:8

EXPOSE 8083

ADD target/airport-bookings-service-0.0.1-SNAPSHOT.jar airport-bookings-service-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "airport-bookings-service-0.0.1-SNAPSHOT.jar"]