FROM java:8

EXPOSE 8084

ADD target/airport-security-service-0.0.1-SNAPSHOT.jar airport-security-service-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "airport-security-service-0.0.1-SNAPSHOT.jar"]